### ISSUE TITLE
DSC causes system to BSOD

### ISSUE THREAD

**Issue by davidobrien1985** [microsoft/BaselineManagement#10]
Hi,

I was given a "GPO export" of the SCM baseline "W2016 Member Server Secpol" and used this module to convert it to DSC. I thought all went well, as I saw no errors, checked the DSC for obvious issues, nothing.
I then went on to bake a new image on AWS Windows Server 2016 Datacenter (vanilla, no config), rebooted the machine and it ended up in a BSOD.
Without a reboot the machine stops responding after a few minutes and just dies.

I was able to reproduce the issue also on Azure VM, same OS.

I uploaded the DSC that I'm applying here: https://gist.github.com/davidobrien1985/b2f01dc4c47329db447e94c8e2e45e41

The only obvious things standing out are the following:

- a lot of registry configs don't have any values
example: https://gist.github.com/davidobrien1985/b2f01dc4c47329db447e94c8e2e45e41#file-dscfromgpo-ps1-L206
The actual `pol` file does have a value attached to it.

Is this a known issue? Does anybody have a working DSC config of this baseline?
I really do not want to apply pol and reg files to my servers.

Thanks!

**Comment by mcmcghee** [comment]
@davidobrien1985 check out the pull request I just submitted. I was having the same issue and those changes fixed it for me.
