### ISSUE TITLE
ConvertFrom-SCMxml not recognized

### ISSUE THREAD

**Issue by Raphdeumax** [microsoft/BaselineManagement#13]
Hi,
I have an error when i convert from SCM to DSC with the command line : 

`ConvertTo-DSC -Type SCMxml -Path 'E:\DSC\Baselines\Windows Server 2012 R2-CPE-Dictionary.xml' -ComputerName Localhost`

The command return : 

```
ConvertFrom-SCMxml : The term ConvertFrom-SCMxml is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:15
```

In order to continue testing I has change the name of the function "ConvertFrom-SCM" to "ConvertFrom-SCMxml" in the BaselineManagement.ps1 and it works but I do not know if this is good practice.

**Comment by bobbytreed** [comment]
This was an old function that was supposed to make it easy to convert from any of the baselines by testing the file extension.  I haven't worked on it in a while, but just updated it to match.
