### ISSUE TITLE
ConvertFrom-ASC - Show-Menu Error

### ISSUE THREAD

**Issue by bdanse** [microsoft/BaselineManagement#14]
running the following command 

`ConvertFrom-ASC -Path .\download\BaselineConfiguration.json`

Results in an Error : 

> Show-Menu : The term 'Show-Menu' is not recognized as the name of a cmdlet, function, script file, or operable program.
>  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At C:\Program Files\WindowsPowerShell\Modules\BaselineManagement\2.8.8809\BaselineManagement.psm1:1410 char:29
> +             $BaselineName = Show-Menu -sMenuTitle "Select a Valid Bas ...
> +                             ~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (Show-Menu:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> Please select a valid Baseline!
> At C:\Program Files\WindowsPowerShell\Modules\BaselineManagement\2.8.8809\BaselineManagement.psm1:1418 char:17
> +                 Throw "Please select a valid Baseline!"
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Please select a valid Baseline!:String) [], RuntimeException
>     + FullyQualifiedErrorId : Please select a valid Baseline!
> 
>

**Comment by bdanse** [comment]
And attempt to fix the issue myself #15

**Comment by bobbytreed** [comment]
Sorry for the hiatus, the Show-Menu function was in Menu.psm1 and the psd1 was not importing it.

**Comment by mgreenegit** [comment]
Closing stale
