### ISSUE TITLE
ASC / UserRightAssignment.ps1 force needed for every setting.

### ISSUE THREAD

**Issue by bdanse** [microsoft/BaselineManagement#18]
The following code is applied successfully but with not result in a compliant state if additional groups are included in the user right assignment. 

src/Parsers/ASC/UserRightsAssignment.ps1
    if ([string]::IsNullOrEmpty($Accounts))
    {
        $policyHash.Force = $true;
    }    
    $policyHash.Policy = $Privilege;
    $policyHash.Identity = $Accounts 

**This will set the user rights as declared** 

   $policyHash.Force = $true;
    $policyHash.Policy = $Privilege;
    $policyHash.Identity = $Accounts

**Comment by bobbytreed** [comment]
Just to clarify, The code above does not work as intended, and you think the IsNullOrEmpty check should be removed? That seems to be the only difference in the code.

**Comment by mgreenegit** [comment]
Closing stale.
