### ISSUE TITLE
wrapping of lines

### ISSUE THREAD

**Issue by davidwallis3101** [microsoft/BaselineManagement#19]
In this example it is wrapping the Arrays, is this expected behaviour?
![image](https://user-images.githubusercontent.com/13855486/37083756-7282df0a-21e8-11e8-977b-6ff8c02038a5.png)

Also a switch to use space indentation would be nice :)

**Comment by mgreenegit** [comment]
I believe this has been fixed. I have not seen the behavior in recent tests.
