### ISSUE TITLE
fix dependencies

### ISSUE THREAD

**Issue by zjalexander** [Microsoft/BaselineManagement#2]
`RequiredModules = @('PSDesiredStateConfiguration', 'GPRegistryPolicyParser', 'SecurityPolicyDSC', 'xAuditPolicy')
`

'PSDesiredStateConfiguration' should be 'PSDscResources'
'xAuditPolicy' should be 'AuditPolicyDsc'

**Comment by ronx** [comment]
Also, SecurityPolicyDSC should probably specify 1.3.0.0 since 1.2.0.0 doesn't have the SecuritySetting resource.

**Comment by nlsdg** [comment]
Current version of BaselineManagement.psd1 has:
54 RequiredModules = @(@{ModuleName = 'AuditPolicyDSC'; ModuleVersion = '1.1.0.0'; },  
55                @{ModuleName = 'SecurityPolicyDSC'; ModuleVersion = '1.3.0.0'; },  
56                'GPRegistryPolicyParser')
If that's satisfactory, you can close this issue.
