### ISSUE TITLE
Issue Import-Module BaselineManagement 

### ISSUE THREAD

**Issue by murasaki718** [microsoft/BaselineManagement#24]
Import-Module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
+ Import-Module BaselineManagement
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by mgreenegit** [comment]
Closing issue. Unable to reproduce error given steps provided.
