### ISSUE TITLE
DSC by default

### ISSUE THREAD

**Issue by timoline** [microsoft/BaselineManagement#29]
These conversion tools are great, good work!
But why not provide the DSC Configurations by default, with pester tests?

**Comment by mgreenegit** [comment]
Can you add more context? Provide from where?

**Comment by timoline** [comment]
:-) it' been a while, I have to check , maybe I was wron and we already can do this with this module

```
# This determines whether or not to output a ConfigurationScript in addition to the localhost.mof
        [switch]$OutputConfigurationScript,

        [switch]$ShowPesterOutput,
```

**Comment by mgreenegit** [comment]
No worries. Closing the issue but feel free to re-open if further discussion is needed.
