### ISSUE TITLE
"wtf" in code :) 

### ISSUE THREAD

**Issue by zjalexander** [microsoft/BaselineManagement#3]
https://github.com/Microsoft/BaselineManagement/search?q=wtf&type=Code&utf8=%E2%9C%93

that was a little surprising to find when my file failed to generate... :)

**Comment by bobbytreed** [comment]
Still an issue?

**Comment by zjalexander** [comment]
yup

**Comment by mgreenegit** [comment]
Fixed in 4.1.1
