### ISSUE TITLE
PowershellAccessControl module import issue with Azure State Configuration

### ISSUE THREAD

**Issue by ZeffyReport** [microsoft/BaselineManagement#30]
Using BaselineManagement to convert GPOs to PS for import into DSC configurations seems to convert the policy correctly, and specified the PowerShellAccessControl module to import into DSC.

Azure State Configuration doesn't have this module, and trying to import the module gives the error "Orchestrator.Shared.AsyncModuleImport.ModuleImportException: An error occurred during module validation."

The module won't import into powershell either.

Grabbing the V4 preview module fails with the error "Orchestrator.Shared.AsyncModuleImport.ModuleImportException: Cannot import the module of name PowerShellAccessControl_v4.0_preview_20150417, as the module structure was invalid."

Is there a version which can be imported and used, or would BaselineManagement need fundamental changes to allow GPOs converted to be imported as DSC configurations?

Thanks in advance.

**Comment by mgreenegit** [comment]
@ZeffyReport how important is access control to you? I can work on switching this to AccessControlDSC, but it is a huge amount of work so I’d like to understand if it is important to you.

**Comment by ZeffyReport** [comment]
The level of ACL control is a "nice to have", but would need greater gravity in request numbers for you to spend the estimated time on migrating to AccessControlDSC. At this time I've removed all ACL settings which cause the error.

Thanks for the reply, but without larger numbers of "me too", I don't think it is a significant missing feature (without wanting to tell you if your time is better spend elsewhere with the community).

**Comment by mgreenegit** [comment]
Thank you for the reply. I will create a new issue for “votes” to track this and get a feel for priority. I want to do it, I just need to get through a couple other projects first. Or, if I can find a resource that accepts sddl’s that might be an option.
