### ISSUE TITLE
PowerShellAccessControl is not on the gallery

### ISSUE THREAD

**Issue by MKletz** [microsoft/BaselineManagement#31]
PowerShellAccessControl should be published to the gallery instead of just being in the "External DSC Resources" folder. We've had to publish this module to our internal nuget instance to make it available to DSC pull servers.

**Comment by mgreenegit** [comment]
@MKletz how important is access control to you? I can work on switching this to AccessControlDSC, but it is a huge amount of work so I’d like to understand if it is important to you.

**Comment by mgreenegit** [comment]
Closing for now but if this is a priority, please just re-open the issue so we can discuss.

**Comment by MKletz** [comment]
Sorry I missed this notification. This wasn't a blocker for us it just prevented the module from being used straight from the gallery.
