### ISSUE TITLE
Read-PolFile

### ISSUE THREAD

**Issue by mcmcghee** [microsoft/BaselineManagement#4]
Where can I get the Read-PolFile function? I can't find any reference to it anywhere except in this module...

```
Read-PolFile : The term 'Read-PolFile' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\BaselineManagement\1.8.0\BaselineManagement.psm1:199 char:29
+         $registryPolicies = Read-PolFile -Path $polFile.FullName
+                             ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Read-PolFile:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by ronx** [comment]
I hit the same issue. Use Parse-PolFile for now. Parse isn't an approved verb, so Bobby submitted a pull request to change it to Read. The request is awaiting approval, so Parse-PolFile can be used in the meantime.

**Comment by bobbytreed** [comment]
I put an if statement in to detect which is availabe and use it.  They still havent' moved on my ridiculously simple pull request 2 years later.
