### ISSUE TITLE
feature idea - Comparing MOFs to RSOP

### ISSUE THREAD

**Issue by MKletz** [microsoft/BaselineManagement#44]
A use tool in the same vein as this for shops moving from GPOs to DSC would be a quick way to compare a MOF file to RSOP data to identify where conflicting settings still exist in the environment.

**Comment by mgreenegit** [comment]
Could this be automated by using the "merge" functionality in BaselineManagement to create a single MOF representing all effective policy settings for a machine, and then "diff" the two mof's?

There is a similar type of tool in the Microsoft Security and Compliance toolkit named Policy Analyzer. It is very powerful but it uses XML as the format for storing information about the policy settings.

**Comment by MKletz** [comment]
I actually didn't know that functionality was in the module. I'll see what I can figure out with the MOF diffing. Thanks!
